### ISSUE TITLE
Shifted double quotes using WOFF file

### ISSUE THREAD

**Issue by mdesantis** [mozilla/Fira#74]
Using the WOFF version double quotes are displayed shifted (Firefox and Chrome on Ubuntu):

![fira-sans-woff-double-quotes-bug](https://cloud.githubusercontent.com/assets/283320/6609068/a4d4dc6c-c84d-11e4-95df-3b4af57fde99.png)

While using the OTF version I don't have this problem. I can reproduce it using this CSS

```css
@font-face {
  font-family: 'Fira Sans';
  src: url('woff/FiraSans-Regular.woff');
  font-weight: 400;
  font-style: normal;
}
```

with [this font file](https://github.com/mozilla/Fira/blob/7e14c60ee00e49320e7b3b165d94bc0853446c29/woff/FiraSans-Regular.woff); if you want I can do a demo page.
